# Site settings
title: Comfy Studio Games
email: contact@comfystudiogames.com
url: http://comfystudiogames.com
description: "Comfy Studio Games are an indie games studio currently developing Robots Minerals Profit."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/ComfyStudioGame

# Build settings
markdown: kramdown
permalink: pretty

# Prose settings
prose:
  rooturl: ''
  siteurl: 'http://www.www.comfystudiogames.com'
  media: 'assets'
  metadata:
    _posts:
      - name: "layout"
        field:
          label: "layout"
          element: "hidden"
          value: "post"
      - name: "date"
        field:
          label: "date"
          element: "text"
          help: "Dates in the future will be published on that date."
          value: "CURRENT_DATETIME"
      - name: "author"
        field:
          label: "author"
          help: "The authors name to be used when displaying this post."
          element: "text"
          placeholder: "Enter name"
      - name: "categories"
        field:
          label: "categories"
          help: "Any categories you would like this post to be grouped under."
          element: "text"
          placeholder: "Enter categories"
      - name: "excerpt"
        field:
          label: "excerpt"
          help: "The preview description that will be shown for this post."
          element: "text"
          placeholder: "Enter excerpt"
      - name: "meta"
        field:
          label: "meta"
          element: "hidden"
          placeholder: "Enter metadata"
      - name: "published"
      	field:
          label: "publish"
          element: "button"
          help: "Should this post be visible or hidden?"
          on: "Visible"
          off: "Hidden"
